#!/bin/sh

docker run --name Abathur -p 3000:3000 -v ~/hellodock/:/root -dit python:2-slim
docker exec Abathur pip install Flask
docker exec -e FLASK_APP=/root/hello.py Abathur flask run --host=0.0.0.0 --port 3000
